# Generated by Django 4.2.27 on 2025-12-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('self_love', 'Self-Love'), ('confidence', 'Confidence'), ('calm', 'Calm & Peace'), ('strength', 'Strength'), ('gratitude', 'Gratitude'), ('growth', 'Growth')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CopingTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('breathing', 'Breathing Exercises'), ('grounding', 'Grounding Techniques'), ('mindfulness', 'Mindfulness'), ('affirmation', 'Affirmations'), ('relaxation', 'Relaxation'), ('cognitive', 'Cognitive Techniques')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('advanced', 'Advanced')], default='easy', max_length=20)),
                ('duration_minutes', models.IntegerField(default=5)),
                ('instructions', models.JSONField(default=list)),
                ('benefits', models.TextField(blank=True)),
                ('when_to_use', models.TextField(blank=True)),
                ('icon', models.CharField(default='🧘', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('inhale_duration', models.IntegerField(blank=True, null=True)),
                ('hold_duration', models.IntegerField(blank=True, null=True)),
                ('exhale_duration', models.IntegerField(blank=True, null=True)),
                ('cycles', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CopingToolUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('mood_before', models.IntegerField(blank=True, null=True)),
                ('mood_after', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coping.copingtool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
