# Generated by Django 4.2.27 on 2025-12-27 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copingtoolusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coping_usages', to=settings.AUTH_USER_MODEL),
        ),
    ]
