# Generated by Django 5.2.4 on 2026-01-09 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapeuticGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('emotion_category', models.CharField(choices=[('anger', 'Anger / Frustration'), ('sadness', 'Sadness / Grief'), ('anxiety', 'Anxiety / Stress'), ('loneliness', 'Loneliness / Isolation'), ('boredom', 'Boredom / Restlessness'), ('love', 'Love / Affection'), ('joy', 'Joy / Excitement'), ('fear', 'Fear / Worry')], max_length=20)),
                ('game_type', models.CharField(choices=[('action', 'Action / Combat'), ('puzzle', 'Puzzle / Brain'), ('creative', 'Creative / Building'), ('social', 'Social / Multiplayer'), ('relaxing', 'Relaxing / Zen'), ('adventure', 'Adventure / Story'), ('sports', 'Sports / Competition'), ('music', 'Music / Rhythm')], max_length=20)),
                ('emoji', models.CharField(default='🎮', max_length=10)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('game_url', models.URLField(blank=True, null=True)),
                ('is_browser_playable', models.BooleanField(default=True)),
                ('therapeutic_benefit', models.TextField(help_text='How this game helps process the emotion')),
                ('intensity_level', models.IntegerField(default=3, help_text='1=mild, 5=intense')),
                ('avg_duration_minutes', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['emotion_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_before', models.CharField(max_length=20)),
                ('emotion_intensity_before', models.IntegerField(default=3, help_text='1-5 scale')),
                ('emotion_after', models.CharField(blank=True, max_length=20, null=True)),
                ('emotion_intensity_after', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.therapeuticgame')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionGameRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_emotion', models.CharField(max_length=20)),
                ('detected_intensity', models.IntegerField(default=3)),
                ('source', models.CharField(choices=[('chat', 'From Chat'), ('journal', 'From Journal'), ('mood', 'From Mood Log'), ('manual', 'User Selected')], max_length=20)),
                ('source_text', models.TextField(blank=True, null=True)),
                ('was_accepted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_recommendations', to=settings.AUTH_USER_MODEL)),
                ('recommended_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='games.therapeuticgame')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
