# Generated by Django 5.2.4 on 2026-01-11 15:11

import django.db.models.deletion
import games.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('game_type', models.CharField(choices=[('tic-tac-toe', 'Tic Tac Toe')], default='tic-tac-toe', max_length=50)),
                ('max_players', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for players'), ('in-progress', 'In Progress'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='waiting', max_length=20)),
                ('game_state', models.JSONField(default=games.models.default_game_state)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('symbol', models.CharField(blank=True, max_length=1)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.multiplayergamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game_session')},
            },
        ),
        migrations.AddField(
            model_name='multiplayergamesession',
            name='players',
            field=models.ManyToManyField(related_name='game_sessions_played', through='games.Player', to=settings.AUTH_USER_MODEL),
        ),
    ]
