# Generated by Django 4.2.27 on 2025-12-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('mood_at_writing', models.IntegerField(blank=True, null=True)),
                ('ai_reflection_enabled', models.BooleanField(default=True)),
                ('ai_reflection', models.TextField(blank=True)),
                ('ai_emotion_analysis', models.JSONField(default=dict)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('category', models.CharField(choices=[('gratitude', 'Gratitude'), ('reflection', 'Self-Reflection'), ('goals', 'Goals & Dreams'), ('emotions', 'Emotional Exploration'), ('relationships', 'Relationships'), ('growth', 'Personal Growth')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
