# Generated by Django 4.2.27 on 2025-12-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField(choices=[(1, '😢 Very Low'), (2, '😔 Low'), (3, '😐 Neutral'), (4, '🙂 Good'), (5, '😊 Great')])),
                ('emotions', models.JSONField(default=list)),
                ('note', models.TextField(blank=True)),
                ('activities', models.JSONField(default=list)),
                ('sleep_quality', models.IntegerField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mood Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('average_mood', models.FloatField()),
                ('dominant_emotions', models.JSONField(default=list)),
                ('patterns', models.TextField()),
                ('suggestions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
