# Generated by Django 5.2.4 on 2026-01-09 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('average_mood', models.FloatField()),
                ('mood_variance', models.FloatField(default=0)),
                ('dominant_emotion', models.CharField(blank=True, max_length=50)),
                ('trend_direction', models.CharField(max_length=20)),
                ('trend_percentage', models.FloatField(default=0)),
                ('summary', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('detected_triggers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mood Analyses',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TriggerPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('time', 'Time-based'), ('topic', 'Topic-based'), ('activity', 'Activity-based'), ('weather', 'Weather-based'), ('social', 'Social'), ('sleep', 'Sleep-related'), ('custom', 'Custom Pattern')], max_length=20)),
                ('emotion_type', models.CharField(choices=[('anxiety', 'Anxiety'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('stress', 'Stress'), ('low_energy', 'Low Energy'), ('overwhelm', 'Overwhelm'), ('loneliness', 'Loneliness'), ('positive', 'Positive Emotion')], max_length=20)),
                ('pattern_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('time_of_day', models.CharField(blank=True, max_length=20, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('keywords', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('suggested_coping', models.JSONField(default=list)),
                ('custom_advice', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score', '-occurrence_count'],
            },
        ),
        migrations.CreateModel(
            name='InsightNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('trigger_alert', 'Trigger Alert'), ('pattern_detected', 'New Pattern'), ('positive_trend', 'Positive Trend'), ('streak_reminder', 'Streak Reminder'), ('coping_suggestion', 'Coping Tip')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_notifications', to=settings.AUTH_USER_MODEL)),
                ('trigger_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='insights.triggerpattern')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
