# Generated by Django 5.2.4 on 2026-01-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerpattern',
            name='all_advice',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='triggerpattern',
            name='therapeutic_note',
            field=models.TextField(blank=True),
        ),
    ]
