# Generated by Django 5.2.4 on 2026-01-09 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('base_image', models.CharField(max_length=100)),
                ('personality', models.CharField(default='friendly', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WellnessPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Buddy', max_length=50)),
                ('happiness', models.IntegerField(default=70)),
                ('energy', models.IntegerField(default=70)),
                ('health', models.IntegerField(default=100)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_interaction', models.DateField(blank=True, null=True)),
                ('unlocked_accessories', models.JSONField(default=list)),
                ('equipped_accessory', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.pettype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('mood_log', 'Mood Check-in'), ('journal', 'Journal Entry'), ('chat', 'Chat Session'), ('breathing', 'Breathing Exercise'), ('coping', 'Coping Exercise'), ('login', 'Daily Login'), ('streak_bonus', 'Streak Bonus')], max_length=20)),
                ('xp_earned', models.IntegerField(default=0)),
                ('happiness_change', models.IntegerField(default=0)),
                ('energy_change', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pet.wellnesspet')),
            ],
            options={
                'verbose_name_plural': 'Pet Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
